query GetPlayers {
  players {
    id
    name
    nickname
    publishedAt
    evaluations(first: 1000) {
      score
      id
      evaluation {
        id
        madeIn
        title
        subject
      }
    }
  }
}
